### ISSUE TITLE
sync artefacts dir check bug (?)

### ISSUE THREAD

**Issue by piejanssens** [engswee/flashpipe#28]
I have an ADO pipeline to sync one or more packages.
I want to sync them to a specific subdirectory using the same name as the package ID.
Before flashpipe is executed, I'm making sure the artifact subdir exists using `mkdir -p`.

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: cpi-package-id
    value: TestPackPieterJanssens 
  - group: flashpipe-dev

resources:
  containers:
    - container: flashpipe
      image: engswee/flashpipe:latest

jobs:
  - job: build
    container: flashpipe
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          git config --global user.email "devops@pipeline.com"
          git config --global user.name "Build Pipeline"
        displayName: 'git config'
      - bash: |
          mkdir -p $(Build.SourcesDirectory)/$(cpi-package-id)
          ls -al
          flashpipe sync --package-id $(cpi-package-id)
        displayName: 'Run sync on using FlashPipe'
        env:
          FLASHPIPE_DEBUG: $(fp-debug)
          FLASHPIPE_TMN_HOST: $(cpi-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(cpi-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(cpi-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(cpi-client-secret)
          FLASHPIPE_DIR_GIT_REPO: $(Build.SourcesDirectory)
          FLASHPIPE_DIR_ARTIFACTS: $(cpi-package-id)
          FLASHPIPE_GIT_COMMIT_MSG: FlashPipe sync ↯
      - bash: git -C $(Build.SourcesDirectory) push origin HEAD:main
        displayName: 'git push'
```

As you can see I'm printing out the contents of the `$(Build.SourcesDirectory)` to validate that indeed the subdirectory exists, but flashpipe complains that the directory does not exist:

```console
Starting: Run sync on using FlashPipe
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.236.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash /__w/_temp/4620447a-1a91-4cc3-a5ed-2770f67d9a2d.sh
total 36
drwxr-xr-x 6 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 .
drwxr-xr-x 6 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 ..
drwxr-xr-x 8 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 .git
-rw-r--r-- 1 vsts_azpcontainer docker_azpcontainer 1254 Mar 21 19:54 FlashPipe-Testpack_Pieter_Janssens.yml
-rw-r--r-- 1 vsts_azpcontainer docker_azpcontainer  893 Mar 21 19:54 FlashPipe-snapshots.yml
-rw-r--r-- 1 vsts_azpcontainer docker_azpcontainer  985 Mar 21 19:54 README.md
drwxr-xr-x 2 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 TestPackPieterJanssens
drwxr-xr-x 4 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 be.deloitte.hrt.csv2xml
drwxr-xr-x 2 vsts_azpcontainer docker_azpcontainer 4096 Mar 21 19:54 snapshots
Usage:
  flashpipe sync [flags]
pe sync [command]


Available Commands:
  apim        Sync API Management artifacts between tenant and Git

Flags:
      --dir-artifacts string            Directory containing contents of artifacts
      --dir-git-repo string             Directory of Git repository
      --dir-naming-type string          Name artifact directory by ID or Name. Allowed values: ID, NAME (default "ID")
      --dir-work string                 Working directory for in-transit files (default "/tmp")
      --draft-handling string           Handling when artifact is in draft version. Allowed values: SKIP, ADD, ERROR (default "SKIP")
      --git-commit-email string         Email used in commit (default "41898282+github-actions[bot]@users.noreply.github.com")
      --git-commit-msg string           Message used in commit (default "Sync repo from tenant")
      --git-commit-user string          User used in commit (default "github-actions[bot]")
      --git-skip-commit                 Skip committing changes to Git repository
  -h, --help                            help for sync
      --ids-exclude strings             List of excluded artifact IDs
      --ids-include strings             List of included artifact IDs
      --package-id string               ID of Integration Package
      --script-collection-map strings   Comma-separated source-target ID pairs for converting script collection references during sync 
      --sync-package-details            Sync details of Integration Package
      --target string                   Target of sync. Allowed values: git, tenant, local(deprecated), remote(deprecated) (default "git")

Global Flags:
      --config string               config file (default is $HOME/flashpipe.yaml)
      --debug                       Show debug logs
      --oauth-clientid string       Client ID for using OAuth
      --oauth-clientsecret string   Client Secret for using OAuth
      --oauth-host string           Host for OAuth token server excluding [https://](https://github.com/engswee/flashpipe/issues/28) 
      --oauth-path string           Path for OAuth token server (default "/oauth/token")
      --tmn-host string             Host for tenant management node of Cloud Integration excluding [https://](https://github.com/engswee/flashpipe/issues/28)
      --tmn-password string         Password for Basic Auth
      --tmn-userid string           User ID for Basic Auth

hpipe sync [command] --help" for more information about a command.

21 Mar 24 19:54 UTC FTL --dir-artifacts [TestPackPieterJanssens] should be a subdirectory of --dir-git-repo [/__w/1/s/]

##[error]Bash exited with code '1'.
Finishing: Run sync on using FlashPipe
```
